function [x,y,z,phi,theta,psi,n] = testEnv_6DOFInitialization
% Provide data for calculations and plotting
% Vertical Range: 292mm-444.5mm
% Horizontal Range: 297mm-444.4mm


n = 300; % Default number of points if not provided

% Define segment proportions relative to n
zero_frac = [0.51, 0.68, 0.84, 0.99]; % Fractions for zero-padding
seg_len = round(n * 0.05); % Length of motion segments

% Generate symbolic paths
x = [zeros(1, round(n * zero_frac(1))), linspace(0, -100, seg_len), ...
    linspace(-100, 100, seg_len), linspace(100, 0, seg_len), ...
    zeros(1, n - 3 * seg_len - round(n * zero_frac(1)))];

y = [zeros(1, round(n * zero_frac(2))), linspace(0, -100, seg_len), ...
    linspace(-100, 100, seg_len), linspace(100, 0, seg_len), ...
    zeros(1, n - 3 * seg_len - round(n * zero_frac(2)))];

z = [zeros(1, round(n * zero_frac(3))) + 292, linspace(292, 192, seg_len), ...
    linspace(192, 392, seg_len), linspace(392, 292, seg_len), ...
    zeros(1, n - 3 * seg_len - round(n * zero_frac(3)))];

phi = [zeros(1, round(n * 0.01)), linspace(0, -45, seg_len), ...
    linspace(-45, 45, seg_len), linspace(45, 0, seg_len), ...
    zeros(1, n - 3 * seg_len - round(n * 0.01))];

theta = [zeros(1, round(n * 0.18)), linspace(0, -45, seg_len), ...
    linspace(-45, 45, seg_len), linspace(45, 0, seg_len), ...
    zeros(1, n - 3 * seg_len - round(n * 0.18))];

psi = [zeros(1, round(n * 0.34)), linspace(0, -45, seg_len), ...
    linspace(-45, 45, seg_len), linspace(45, 0, seg_len), ...
    zeros(1, n - 3 * seg_len - round(n * 0.34))];

end
